accounts/urls.py
"""Defines URL patterns for accounts."""

from django.urls import path, include

from . import views


app_name = 'accounts'
urlpatterns = [
    # Include default auth urls.
    path('', include('django.contrib.auth.urls')),
    # Registration page.
    path('register/', views.register, name='register'),
]

achaproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('mikelapps.urls')),

]

mikelapps/urls.py
"""Defines URL patterns for mikelapps."""

from django.urls import path

from . import views

app_name = 'mikelapps'
urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    # Page that shows all products.
    path('products/', views.products, name='products'),
    # Detail page for a single product.
    path('products/<int:product_id>/', views.product, name='product'),
    # Page for adding a new product.
    path('new_product/', views.new_product, name='new_product'),
    # Page for adding a new entry.
    path('new_entry/<int:product_id>/', views.new_entry, name='new_entry'),
    # Page for editing an entry.
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
]

accounts/models.py
from django.db import models

# Create your models here.

mikelapps/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Product(models.Model):
    """A product the user is learning about."""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        """Return a string representation of the model."""
        return self.text


class Entry(models.Model):
    """Something specific learned about a product."""
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """Return a simple string representing the entry."""
        return f"{self.text[:50]}..."

mikelapps/forms.py
from django import forms

from .models import Product, Entry


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['text']
        labels = {'text': ''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

accounts/views.py
#from django.shortcuts import render
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

# Create your views here.
def register(request):
    """Register a new user."""
    if request.method != 'POST':
        # Display blank registration form.
        form = UserCreationForm()
    else:
        # Process completed form.
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # Log the user in and then redirect to home page.
            login(request, new_user)
            return redirect('mikelapps:index')

    # Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'registration/register.html', context)

mikelapps/views.py
#from django.shortcuts import render
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404

from .models import Product, Entry
from .forms import ProductForm, EntryForm

# Create your views here.

def index(request):
    """The home page for Mikel App."""
    return render(request, 'mikelapps/index.html')

@login_required
def products(request):
    """Show all products."""
    products = Product.objects.filter(owner=request.user).order_by('date_added')
    context = {'products': products}
    return render(request, 'mikelapps/products.html', context)

@login_required
def product(request, product_id):
    """Show a single product and all its entries."""
    product = Product.objects.get(id=product_id)
    # Make sure the product belongs to the current user.
    if product.owner != request.user:
        raise Http404

    entries = product.entry_set.order_by('-date_added')
    context = {'product': product, 'entries': entries}
    return render(request, 'mikelapps/product.html', context)

@login_required    
def new_product(request):
    """Add a new product."""
    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = ProductForm()
    else:
        # POST data submitted; process data.
        form = ProductForm(data=request.POST)
        if form.is_valid():
            new_product = form.save(commit=False)
            new_product.owner = request.user
            new_product.save()
            return redirect('mikelapps:products')

    # Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'mikelapps/new_product.html', context)

@login_required    
def new_entry(request, product_id):
    """Add a new entry for a particular product."""
    product = Product.objects.get(id=product_id)
    
    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = EntryForm()
    else:
        # POST data submitted; process data.
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.product = product
            new_entry.save()
            return redirect('mikelapps:product', product_id=product_id)

    # Display a blank or invalid form.
    context = {'product': product, 'form': form}
    return render(request, 'mikelapps/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    """Edit an existing entry."""
    entry = Entry.objects.get(id=entry_id)
    product = entry.product
    if product.owner != request.user:
        raise Http404

    if request.method != 'POST':
        # Initial request; pre-fill form with the current entry.
        form = EntryForm(instance=entry)
    else:
        # POST data submitted; process data.
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('mikelapps:product', product_id=product.id)

    context = {'entry': entry, 'product': product, 'form': form}
    return render(request, 'mikelapps/edit_entry.html', context)

mikelapps/templates/mikelapps/base.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Home</title>

  {% load django_bootstrap5 %}
  {% bootstrap_css %}
  {% bootstrap_javascript %}

</head>
<body>
  <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'mikelapps:index' %}">
          Home</a>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
        data-bs-target="#navbarCollapse" aria-controls="navbarCollapse"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'mikelapps:products' %}">
              Products</a></li>
        </ul> <!-- End of links on left side of navbar -->

        <!-- Account-related links -->
        <ul class="navbar-nav ms-auto mb-2 mb-md-0">

          {% if user.is_authenticated %}
            <li class="nav-item">
              <span class="navbar-text me-2">Hello, {{ user.username }}.
                </span></li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:register' %}">
                  Register</a></li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:login' %}">
                  Log in</a></li>
          {% endif %}

        </ul> <!-- End of account-related links -->

        {% if user.is_authenticated %}
          <form action="{% url 'accounts:logout' %}" method='post'>
            {% csrf_token %}
            <button name='submit' class='btn btn-outline-secondary btn-sm'>
              Log out</button>
          </form>
        {% endif %}

      </div> <!-- Closes collapsible parts of navbar -->

    </div> <!-- Closes navbar's container -->
  </nav> <!-- End of navbar -->

  <main class="container">
    <div class="pb-2 mb-2 border-bottom">
      {% block page_header %}{% endblock page_header %}
    </div>

    <div>
      {% block content %}{% endblock content %}
    </div>
  </main>

</body>
</html>

mikelapps/templates/mikelapps/edit_entry.html
{% extends "mikelapps/base.html" %}
{% load django_bootstrap5 %}

{% block page_header %}
  <h2>Edit entry</h2>
{% endblock page_header %}

{% block content %}

  <p><a href="{% url 'mikelapps:product' product.id %}">{{ product }}</a></p>

  <form action="{% url 'mikelapps:edit_entry' entry.id %}" method='post'>
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button button_type="submit" content="Save changes" %}
  </form>

{% endblock content %}

mikelapps/templates/mikelapps/index.html
{% extends 'mikelapps/base.html' %}

{% block page_header %}
  <div class="p-3 mb-4 bg-light border rounded-3">
    <div class="container-fluid py-4">
      <h1 class="display-3">Welcome to system!</h1>
      
      <p class="lead">You are about to enter a platform that will allow
          you to manage and administer your products and their information using qrcodes.
          With this tool, you will be able to efficiently track your inventories,
          speed up your sales processes and have greater control over your products.</p>

      <a class="btn btn-primary btn-lg mt-1"
          href="{% url 'accounts:register' %}">Register &raquo;</a>
    </div>
  </div>
{% endblock page_header %}

mikelapps/templates/mikelapps/new_entry.html
{% extends "mikelapps/base.html" %}
{% load django_bootstrap5 %}

{% block page_header %}
  <h2>Add a new entry.</h2>
{% endblock page_header %}

{% block content %}

  <p><a href="{% url 'mikelapps:product' product.id %}">{{ product }}</a></p>

  <form action="{% url 'mikelapps:new_entry' product.id %}" method='post'>
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button button_type="submit" content="Add entry" %}
  </form>

{% endblock content %}

mikelapps/templates/mikelapps/new_product.html
{% extends "mikelapps/base.html" %}
{% load django_bootstrap5 %}

{% block page_header %}
  <h2>Add a new product.</h2>
{% endblock page_header %}

{% block content %}

  <p>Product:</p>
  <form action="{% url 'mikelapps:new_product' %}" method='post'>
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button button_type="submit" content="Add product" %}
  </form>

{% endblock content %}

mikelapps/templates/mikelapps/product.html
{% extends 'mikelapps/base.html' %}

{% block page_header %}
  <h1>{{ product.text }}</h1>
{% endblock page_header %}

{% block content %}

  <p>
    <a href="{% url 'mikelapps:new_entry' product.id %}">Add new entry</a>
  </p>

  {% for entry in entries %}
    <div class="card mb-3">
      <!-- Card header with timestamp and edit link -->
      <h4 class="card-header">
        {{ entry.date_added|date:'M d, Y H:i' }}
        <small><a href="{% url 'mikelapps:edit_entry' entry.id %}">
          edit entry</a></small>
      </h4>
      <!-- Card body with entry text -->
      <div class="card-body">{{ entry.text|linebreaks }}</div>
    </div>
  {% empty %}
    <p>There are no entries for this product yet.</p>
  {% endfor %}

{% endblock content %}

mikelapps/templates/mikelapps/products.html
{% extends 'mikelapps/base.html' %}

{% block page_header %}
  <h1>Products</h1>
{% endblock page_header %}

{% block content %}

  <ul class="list-group border-bottom pb-2 mb-4">
    {% for product in products %}
      <li class="list-group-item border-0">
        <a href="{% url 'mikelapps:product' product.id %}">
          {{ product.text }}</a>
      </li>
    {% empty %}
      <li class="list-group-item border-0">No products have been added yet.</li>
    {% endfor %}
  </ul>

  <a href="{% url 'mikelapps:new_product' %}">Add a new product</a>

{% endblock content %}